export const COMIENZAR_LOGIN_USER = 'COMIENZAR_LOGIN_USER';
export const LOGIN_USER_EXITOSA = 'LOGIN_USER_EXITOSA';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const COMIENZAR_DESCARGA_AGREGADORES = 'COMIENZAR_DESCARGA_AGREGADORES';
export const DESCARGA_AGREGADORES_EXITOSA = 'DESCARGA_AGREGADORES_EXITOSA';
export const DESCARGA_AGREGADORES_ERROR = 'DESCARGA_AGREGADORES_ERROR';